version: '3'

services:
  web:
    ports:
      - "80:80"
    build: ./.docker/php
    volumes:
      - ./www:/var/www
    user: "1001:1001"

  db:
    image: mysql:5.6
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/db/data:/var/lib/mysql
      - ./.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306